image:
  file: .gitpod.Dockerfile
tasks:
  - init: javac app.java
    command: java app
ports:
  - port: 6080
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore